### ISSUE TITLE
Add version management support

### ISSUE THREAD

**Issue by etki** [ayte-io/steward#3]
Resulting interface should look kinda like following:

```
steward version get
steward version set %version%
steward version major get
steward version major set %value%
steward version major bump
steward version minor get
steward version minor set %value%
steward version minor bump
steward version patch get
steward version patch set %value%
steward version patch bump
steward version build get
steward version build set %value%
steward version build discard
steward version classifier get
steward version classifier set %value%
steward version classifier discard
```

```yaml
# steward.yml
version:
  paths:
    - path: metadata.rb
      strategy: ChefCookbook
    - path: VERSION
      strategy: SimpleFile
```
